module.exports = {
	'Go': ['*.go'],
	'Rust': ['*.rs', '*.rlib'],
	'C++': ['*.cc', '*.C', '*.cxx', '*.c++', '*.hh', '*.hxx', '*.hpp', '*.h++'],
	'Kotlin': ['*.kt', '*.kts'],
	'Swift': ['*.swift'],
	'Java': ['*.java'],
	'Python': ['*.py'],
	'CMake': ['*.cmake'],
	'Perl': ['*.pl'],
	'Objective-C': ['*.m'],
	'Objective-C++': ['*.mm'],
	'C': ['*.c', '*.h'],
	'JavaScript': ['*.js'],
	'Yacc': ['*.y'],
	'LLVM': ['*.ll'],
	'HTML': ['*.html', '*.htm'],
	'Dockerfile': ['.dockerfile'],
	'Lex': ['*.lex'],
	'Shell': ['*.sh'],
	'CSS': ['*.css'],
	'Ruby': ['*.rb'],
	'Makefile': ['makefile'],
	'PHP': ['*.php'],
	'Assembly': ['*.asm', '*.s'],
	'Basic': ['*.b']
}